const { Schema } = require('mongoose');

const issueSchema = new Schema(
  {
    // _id      : String   // Made automaticaly by DBserver, unique
    project     : String,
    issue_title : String,  //
    issue_text  : String,  //
    created_by  : String,  //
    assigned_to : {
      type    : String,
      default : '',
    },  //Op, def to ''
    status_text : {
      type    : String,
      default : '',
    },  //Op  def to ''
    // created_on  : Date,    //Autogenerated by timestamps option below
    // updated_on  : Date,    //Autogenerated by timestamps option below
    open        : {
      type    : Boolean,
      default : true,
    }, // 
  },{
    timestamps : {
      createdAt: 'created_on',
      updatedAt: 'updated_on',
    }
  }
);

module.exports = issueSchema;